services:
  db:
    image: "postgres:11-alpine"
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
  api:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://user:secret@db:5432/cashdb
    depends_on:
      - db
